# Práctica 1 Reconocimiento de Formas: Clasificador de la distancia euclídea 

* **Alumno 1**:
* **Alumno 2**:


In [154]:

import numpy as np
from abc import abstractmethod

class Classifier:

    @abstractmethod
    def fit(self,X,y):
        pass

    @abstractmethod
    def predict(self,X):
        pass

class ClassifEuclid(Classifier):
    ocurrences = ()
    def __init__(self,labels=[]):
        """Constructor de la clase
        labels: lista de etiquetas de esta clase"""
        self.labels=labels
        pass

    def fit(self,X,y):
        """Entrena el clasificador
        X: matriz numpy cada fila es un dato, cada columna una medida
        y: vector de etiquetas, tantos elementos como filas en X
        retorna objeto clasificador"""
        self.predict(X)
        return self

    def predict(self,X):
        """Estima el grado de pertenencia de cada dato a todas las clases 
        X: matriz numpy cada fila es un dato, cada columna una medida del vector de caracteristicas. 
        Retorna una matriz, con tantas filas como datos y tantas columnas como clases tenga
        el problema, cada fila almacena los valores pertenencia de un dato a cada clase""" 
        ocurrences = np.unique(self.labels,return_counts=True)
        result = np.zeros((X.shape[0],ocurrences[0].size))
        begin = 0
        end = 0
        i = 0
        for element in ocurrences[1]:
            end +=element
            result[:,i] = np.divide(np.sum(X, axis=1),np.mean(np.sum(X[begin:end], axis=1)))
            begin +=element
            i+=1
        return result
    
    def pred_label(self,X):
        """Estima la etiqueta de cada dato. La etiqueta puede ser un entero o bien un string.
        X: matriz numpy cada fila es un dato, cada columna una medida
        retorna un vector con las etiquetas de cada dato"""
        result = []
        for element in X:
            index = (np.abs(element - 1)).argmin()
            result.append(index)
        return result
    
    def num_aciertos(self,X,y):
        """Cuenta el numero de aciertos del clasificador para un conjunto de datos X.
        X: matriz de datos a clasificar
        y: vector de etiquetas correctas"""
        aux = (list(b==y).count(True))
        return (aux/ len(X))*100


## Código para cargar la base de datos desde un fichero en drive:

In [155]:
# from google.colab import drive
# from sklearn.datasets import load_iris

# drive.mount('/content/gdrive')
# drive_dir = '/content/gdrive/My Drive/Colab Notebooks/'

# import pandas as pd
# # Cargar las características de la BD
# X = np.genfromtxt(drive_dir + 'irisData.txt', delimiter='\t')[:, :-1]
# print("X: \n" + str(X))

# # Leer las etiquetas y convertirlas a enteros
# y = np.genfromtxt(drive_dir + 'irisData.txt', dtype=str, delimiter='\t')[:, -1]
# y = pd.factorize(y)[0]
# print("y: \n" + str(y))

## Código para cargar la base de datos Iris directamente desde sklearn:

In [160]:
from sklearn.datasets import load_iris
import numpy as np
dataset = load_iris()
X = dataset.data
y = dataset.target
result = np.zeros((X.shape[0],1))
idx = (np.abs(X - 1)).argmin() 
print(idx)
var = ClassifEuclid(y)
print(var.predict(X))
print(var.pred_label(a))
var.num_aciertos(b,y)

    

90
[[1.00571879 0.71368598 0.59509918]
 [0.93669888 0.66470753 0.55425904]
 [0.92683889 0.65771061 0.54842474]
 [0.92683889 0.65771061 0.54842474]
 [1.00571879 0.71368598 0.59509918]
 [1.12403865 0.79764903 0.66511085]
 [0.95641885 0.67870137 0.56592765]
 [0.9958588  0.70668906 0.58926488]
 [0.87753895 0.622726   0.51925321]
 [0.94655886 0.67170445 0.56009335]
 [1.06487872 0.75566751 0.63010502]
 [0.98599882 0.69969214 0.58343057]
 [0.9169789  0.65071369 0.54259043]
 [0.83809899 0.59473832 0.49591599]
 [1.10431867 0.78365519 0.65344224]
 [1.18319858 0.83963056 0.70011669]
 [1.0845987  0.76966135 0.64177363]
 [1.01557878 0.7206829  0.60093349]
 [1.13389864 0.80464596 0.67094516]
 [1.05501873 0.74867058 0.62427071]
 [1.05501873 0.74867058 0.62427071]
 [1.05501873 0.74867058 0.62427071]
 [0.92683889 0.65771061 0.54842474]
 [1.04515875 0.74167366 0.61843641]
 [1.01557878 0.7206829  0.60093349]
 [0.96627884 0.68569829 0.57176196]
 [1.02543877 0.72767982 0.60676779]
 [1.02543877 0.72767982 0

86.66666666666667

Entrenamiento, predicción y evaluación

In [105]:
# 1. Cargar los datos de la base de datos de entrenamiento

# 2. Entrenar el clasificador

# 3. Predecir empleando la base de datos de entrenamiento (X)

# 4. Evaluar el clasificador calculando el porcentaje de datos correctamente clasificados

Repite el proceso anterior para las base de datos "wine" y "cancer"

Resultados de los tres experimentos:

| Base de datos | Número de aciertos | Porcentaje de aciertos |
| --- | --- | --- |
| Iris   |  |  |
| Wine   |  |  |
| Cancer |  |  |
